version: "2"
services:
  zookeeper:
    image: ${REPOSITORY}/cp-zookeeper:${TAG}
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: ${REPOSITORY}/cp-kafka:${TAG}
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: "1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "SASL_PLAINTEXT://kafka:9092"
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: "1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN,SCRAM
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/kafka_jaas.conf
    volumes:
        - $PWD/secrets:/etc/kafka/secrets

  client:
    image: ${REPOSITORY}/cp-kafka:${TAG}
    container_name: client
    hostname: client
    depends_on:
        - kafka
    volumes:
        - $PWD/secrets:/etc/kafka/secrets
